import Footer from "@/components/Footer";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children, 
}: {
  children: React.ReactNode;
}) {
  const sutu = "sutu"
  const concuasutu = "son"
  const ga = "ga"
  const ga1 = 1
  const feature3 = 3.1
  const feature32 = 3.2
  const feature33 = 3.3
  const feature4 = 4
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
